### PR TITLE
Better testing and automation.

### PR DESCRIPTION
**Pull request by awltux**
Added a setup.sh to install or upgrade local install.
Added a test directory to contain tests against MTD test environment.
Added a test/unit-test.sh to launch test commands.
Added a new test gnucash account that matches data in MTD test environment.
Added a default config file in the user HOME directory that fills the config file with the relevant gnucash accounts.
Auto fill VRN from test user details.
Added/Modified headers in fraud headers after feedback from MTD developers.
Fixed some Win8-specific issues.
Fixed IP and MAC detection - was picking seemingly random I/F on my host.

### CODE REVIEW

**Comment by awltux** [comment]
Sorry, had a couple of changes I wanted to get in.
All done now.

**Comment by cybermaggedon** [comment]
Thanks for the MR, I'm taking a look now, couple of things to look at...

`WindowsSelectorEventLoopPolicy` is only available on Windows, not Mac or Linux. I get...
```
Exception: module 'asyncio' has no attribute 'WindowsSelectorEventLoopPolicy'
sys:1: RuntimeWarning: coroutine 'run' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
I'm guessing that's only needed in Windows also. I don't regularly have a working Windows machine to test this out.  Would this work...?

```
    if hasattr(asyncio, "WindowsSelectorEventLoopPolicy"):
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

**Comment by cybermaggedon** [comment]
I'm also thinking that the terms and conditions screen isn't needed, T&Cs are integrated with the HMRC authentication. Developers put privacy docs and T&Cs document into the application when they submit, and these docs are shown to users in the web before they grant permission.  Screenshot attached of page 2 on the standard user auth flow, the link, bottom-right on the auth screen jumps to gnucash-uk-vat T&Cs (it's a link to the LICENCE file in Github).

asd

**Comment by awltux** [comment]
I'll double check, but I intended to only display the t&c url if it's
defined in the user config. That way it will work as-is by default.
If that's not the case, I'll refactor to do that if needs be. Let me check.

**Comment by awltux** [comment]
I'll put a windows condition round it.

**Comment by cybermaggedon** [comment]
> I'll double check, but I intended to only display the t&c url if it's defined in the user config.

OK, that's fine by me. I noticed there's an example.com link added to the config by default, so if that's not there, it's good to go.

**Comment by cybermaggedon** [comment]
I ran some commands on yesterday, and it all passes in the new Fraud API console. :smile:

**Comment by cybermaggedon** [comment]
The new test directory is monumentally awesome!  Just getting started.

**Comment by awltux** [comment]
Thanks, ... standing on the shoulder of giants and all that :-)

I received my production approval yesterday and realised there are some
additional changes I want to make to unit-test.sh so it can be used to
launch the production commands.
Currently, I have to revert back to the full python command for prod, which
is prone to mistakes, so I'll probably have some more changes to submit
before the pull request is to my satisfaction.
Hope you don't mind. You can cancel the pull request for now if you want
(or just ignore it).

HMRC team also pointed me towards the Test Data
<https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#sandbox-data_retrieve-vat-obligations-get>
section of the docs. Has some interesting possibilities which I
wasn't aware of. But that's probably for another day.

Kind regards,
Chris

**Comment by cybermaggedon** [comment]
The things you are changing are all in the 'test' directory, so I'm happy to treat that as a work-in-progress; it hasn't broken anything.

So I suggest....
- Remove the T&Cs entry from default configuration creation
- Check for Windows event loop thing
and then we're good to merge. Subsequent MR for further work on the test dir.

But happy to leave this MR open if that's your preference.

Btw, the test dir doesn't work for me, minor configuration stuff to do with Linux Python, so there's a few tweaks I can try out, and you can review if you're OK with that.

**Comment by awltux** [comment]
Took me a bit longer to get back to this than I was planning, but that should be my changes complete. I used it to submit to prod as well, so very pleased. Hope you find the changes compatible and of use. Let me know if there is anything else I need to look at.

**Comment by cybermaggedon** [comment]
Sorry for the delay, have been busy hoping to take a look today or tomorrow

**Pull request merged**
